### ISSUE TITLE
Implement `claim` module

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#863]
Initial implementation for `claim` module

## Tasks
- [x] https://github.com/tendermint/spn/issues/782
- [x] https://github.com/tendermint/spn/issues/783
- [x] https://github.com/tendermint/spn/issues/784
- [x] https://github.com/tendermint/spn/issues/785
- [x] https://github.com/tendermint/spn/issues/834
- [x] https://github.com/tendermint/spn/issues/835
- [x] https://github.com/tendermint/spn/issues/851
- [x] https://github.com/tendermint/spn/issues/861
- [x] https://github.com/tendermint/spn/issues/862
