### ISSUE TITLE
Implement `mint` module

### ISSUE THREAD

**Issue by lubtd** [tendermint/spn#864]
Initial implementation of `mint` module

## Tasks
- [ ] https://github.com/tendermint/spn/issues/780
- [ ] https://github.com/tendermint/spn/issues/781
- [ ] https://github.com/tendermint/spn/issues/809
- [ ] https://github.com/tendermint/spn/issues/852
