### ISSUE TITLE
Prepare for Cosmos SDK `v0.46.x`

### ISSUE THREAD

**Issue by aljo242** [tendermint/spn#909]
**Is your feature request related to a problem? Please describe.**

Cosmos SDK `v0.46.x` is  a heavily API-breaking update.  In order to update `spn` the following must be done:
- [x] remove depreceated `rest` API imports https://github.com/tendermint/spn/pull/908
- [x] remove the usage of `sdk.Int.ToDec()`
- [x] decouple `spn` from `ignite` (this will avoid the current circular dependency)
- [X] upgrade `ibc-go` to a version that is compliant with Cosmos SDK `v0.46.x`
- [X] upgrade the imported `x/fundraising` module for compliance with Cosmos SDK `v0.46.x`

The `ignite` CLI depends on `spn` so this is a critical task that must be completed before `spn` can be upgraded in order to enable `ignite` to be upgraded
